import os
import re

path = r'D:\Projects\BMad\SmileGardenVoiceAgent\server\src\agent.py'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

# I will completely replace the log_call_to_supabase function with a highly robust version with deep logging
pattern = r'async def log_call_to_supabase\(caller_id, start_time, room_name, agent\):.*?(?=\n\s*\n\s*def prewarm|\Z)'
new_func = '''async def log_call_to_supabase(caller_id, start_time, room_name, agent):
    try:
        logger.info(f"========== STARTING LOG_CALL_TO_SUPABASE FOR ROOM {room_name} ==========")
        from sentiment import analyze_sentiment_and_summarize
        import storage
        duration = int(time.time() - start_time)

        # Retrieve session state
        state = session_states.get(room_name, {})
        outcome = "booked_appointment" if state.get("booked_appointment") else "assistance_provided"

        # Get the audio URL generated by LiveKit Egress
        audio_url = storage.get_public_audio_url(f"{room_name}.mp3")

        final_caller_id = caller_id
        if caller_id.startswith("user-") and state.get("phone_number_collected"):
            final_caller_id = state.get("phone_number_collected")

        logger.info("Extracting transcript...")
        transcript_lines = []
        if agent and hasattr(agent, 'chat_ctx') and agent.chat_ctx:
            # Handle both property and method depending on LiveKit version
            messages = agent.chat_ctx.messages() if callable(agent.chat_ctx.messages) else agent.chat_ctx.messages
            for msg in messages:
                role = msg.role.capitalize() if hasattr(msg, 'role') else 'Unknown'
                content = getattr(msg, 'content', '')
                if isinstance(content, list):
                    text = " ".join([c if isinstance(c, str) else getattr(c, "text", "") for c in content])
                else:
                    text = content
                transcript_lines.append(f"{role}: {text}")
        else:
            logger.warning("agent.chat_ctx is missing or None!")
            
        transcript_text = "\n".join(transcript_lines)
        if not transcript_text.strip():
            transcript_text = "No transcript could be extracted."

        logger.info(f"Analyzing sentiment... Transcript length: {len(transcript_text)}")
        analysis = await analyze_sentiment_and_summarize(transcript_text)

        if supabase:
            logger.info("Inserting into Supabase...")
            supabase.table("calls").insert({
                "caller_number": final_caller_id,
                "duration_seconds": duration,
                "status": "completed",
                "outcome": outcome,
                "transcript": transcript_text,
                "sentiment": analysis.get("sentiment", "Neutral"),
                "summary": analysis.get("summary", "Call ended."),
                "audio_url": audio_url
            }).execute()
            logger.info("========== Successfully logged call to Supabase! ==========")
        else:
            logger.error("Supabase client not initialized!")

        if room_name in session_states:
            del session_states[room_name]
    except Exception as e:
        logger.error(f"========== CRITICAL ERROR IN LOG_CALL_TO_SUPABASE: {e} ==========")
        import traceback
        logger.error(traceback.format_exc())'''

content = re.sub(pattern, new_func, content, flags=re.DOTALL)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
print('Successfully patched log_call_to_supabase with robust error handling and logging')
