import asyncio
import time
import os
import json
from dotenv import load_dotenv
from supabase import create_client, Client

load_dotenv("D:\Projects\BMad\SmileGardenVoiceAgent\server\.env")

supabase_url = os.getenv("NEXT_PUBLIC_SUPABASE_URL", "")
supabase_key = os.getenv("NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY", "")
supabase = create_client(supabase_url, supabase_key)

try:
    print("Attempting to insert dummy call into Supabase...")
    res = supabase.table("calls").insert({
        "caller_number": "test_user_from_script",
        "duration_seconds": 45,
        "status": "completed",
        "outcome": "assistance_provided",
        "transcript": "User: Hello\nAgent: Hi there",
        "sentiment": "Neutral",
        "summary": "This is a test call generated by the debugging script.",
        "audio_url": "https://example.com/audio.mp3"
    }).execute()
    print("Insert successful!")
    print(res.data)
except Exception as e:
    print("Insert failed!")
    print(str(e))
